### ISSUE TITLE
Not available for installation via composer

### ISSUE THREAD

**Issue by vasilii-b** [HamzaHannad/Magento2-SlackLogger#1]
![image](https://github.com/user-attachments/assets/49eab56e-d562-43a1-904e-c9e32ce1ae76)

`composer.json` file

```json
...
"repositories": {
        "magify-magento2-module-slacknotifier": {
            "type": "vcs",
            "url": "https://github.com/HamzaHannad/Magento2-SlackLogger"
        }
    },
...
```

this is due to the missing release.

To solve the problem, create a new release as the module version

**Comment by HamzaHannad** [comment]
Hi @vasilii-b 

Thank you for bringing this to my attention!

I have created a new release for the Magento 2 Slack Notifier module, which includes the necessary version tag.

This should resolve the issue with the missing release.

Please let me know if you have any further questions or run into any other issues!

Best regards,
Hamza

**Comment by vasilii-b** [comment]
@HamzaHannad this is now solved. Thanks!
